### ISSUE TITLE
 'spectacularAI.depthai.Pipeline' object has no attribute 'ext'

### ISSUE THREAD

**Issue by patrickpoirier51** [SpectacularAI/sdk#2]
Hello,

I have this error loading ros2 launch launch/mapping.py from ros2-integration2

[ros2_node-1]   ... spectacularAI_ros2/install/spectacularai_depthai/lib/python3.8/site-packages/spectacularai_depthai/ros2_node.py", line 130, in __init__
[ros2_node-1]     self.vio_pipeline.ext.rae.front.colorLeft.setFps(fps)
[ros2_node-1] AttributeError: 'spectacularAI.depthai.Pipeline' object has no attribute 'ext'

        fps = 15 # 20 Would be better but is slower.
        self.vio_pipeline.ext.rae.front.colorLeft.setFps(fps)
        self.vio_pipeline.ext.rae.front.colorRight.setFps(fps)

I run with
Python                                  3.8.10
spectacularAI                       1.21.0
depthai                                 2.22.0.0
numpy                                  1.24.4

Best regards

**Comment by Bercon** [comment]
You can just remove those 3 lines, they aren't required with normal OAK-Ds

**Comment by patrickpoirier51** [comment]
Thanks for your fast answer

I already tried that , thanks
But now, and it now crash down the script with this error

[ros2_node-1]   File "/home/aaeon/spectacularAI_ros2/install/spectacularai_depthai/lib/python3.8/site-packages/spectacularai_depthai/ros2_node.py", line 134, in __init__
[ros2_node-1]     self.vio_session = self.vio_pipeline.startSession(self.device)
[ros2_node-1] RuntimeError: Spectacular AI SDK:  error: invalid or unsupported color input resolution 720p

Best regards

**Comment by Bercon** [comment]
Depending on your OAK-D model, it might require setting 400p/800p resolution. I'd recommend debugging using https://github.com/SpectacularAI/sdk-examples/blob/main/python/oak/vio_record.py and https://github.com/SpectacularAI/sdk-examples/blob/main/python/oak/mapping_ros.py for example what the settings should be and then replicate them with this code. The ROS2 Python example is still WIP and not fully tested

**Comment by Bercon** [comment]
The ros2 example is now part of the sdk-examples and has been updated to work on normal OAK-D cameras. You'll find it at https://github.com/SpectacularAI/sdk-examples/tree/main/python/oak/ros2
