### ISSUE TITLE
spectacularAI_native detail

### ISSUE THREAD

**Issue by tjucaokun** [SpectacularAI/sdk#29]
May I get the spectacularAI_native source code? I want to try some new vislam algorithms based on your framework. Thank u very much!!

**Comment by oseiskar** [comment]
Hello. Thank you for your interest, but those parts of the plugin source code are proprietary and not available to third parties

**Comment by tjucaokun** [comment]
> Hello. Thank you for your interest, but those parts of the plugin source code are proprietary and not available to third parties

Thank you for your reply and I apologize for my impolite behavior！
