### ISSUE TITLE
Wheel for Jetson Nano?

### ISSUE THREAD

**Issue by mgagvani** [SpectacularAI/sdk#3]
How can I install the Spectacular AI SDK on the Jetson Nano? On [PyPI](https://pypi.org/project/spectacularAI/#files) there are only files available for x86.

**Comment by oseiskar** [comment]
The ARM build is only available with a commercial license: https://www.spectacularai.com/#contact

**Comment by mgagvani** [comment]
Thank you @oseiskar. I filled out the contact form and would appreciate it if you could consider our request.
