### ISSUE TITLE
realsense record keep spinning.

### ISSUE THREAD

**Issue by RenanMoreiraPinto** [SpectacularAI/sdk#43]
everytime i try to use the sdk record version on realsense the visualizar keep spinning until crash and complain about imu time, there is a way of change the settings?

./sai-record-realsense 
Recording to 'data/2024-07-01_11-36-18'
SpectacularAI WARN: Large time gap between IMU samples: 0.2307s
SpectacularAI WARN:   Gaps in IMU data may cause frame drops and degrade VIO accuracy.

**Comment by oseiskar** [comment]
Sorry, this is a bit too vague to be answered. Possible causes:
1. The host laptop / computer is underpowered
2. Bad OpenGL drivers (visualization too slow)
3. Bad USB connection

You can also try the other RealSense tools listed here https://spectacularai.github.io/docs/sdk/wrappers/realsense.html (e.g., `./vio_jsonl` or `./sai-record-realsense --recording_only --no_preview`) to troubleshoot the cause in more detail

**Comment by RenanMoreiraPinto** [comment]
The pc  have2  NVIDIA RTX A2000 12GB   --
driver are uptodate using nerfstudio conda enviroment
sai-cli not include realsense option ..

imu is calibrate i tryed using the minimal and max range still no help it all
using , ./vio_jsol
{"acceleration":{"x":9.785415358376519e-05,"y":0.0010019241161117849,"z":0.0020052463955156138},"angularVelocity":{"x":0.25833097100257874,"y":0.22731250524520874,"z":0.26385918259620667},"orientation":{"w":-0.460489808458803,"x":0.1775095392681633,"y":-0.821089474316956,"z":0.28679467699989514},"position":{"x":-0.14735036052383874,"y":-0.627360202779824,"z":-0.39133743992276293},"status":"TRACKING","time":1719861768.4407866,"velocity":{"x":0.11017534277195007,"y":-0.3243633938528007,"z":-0.22449938619525425}}
{"acceleration":{"x":5.4170885268532164e-05,"y":0.0009353164157522037,"z":0.001899464392855762},"angularVelocity":{"x":0.2550891935825348,"y":0.17208264768123627,"z":0.2563660740852356},"orientation":{"w":-0.4689762725575783,"x":0.17542690603587188,"y":-0.8173383519579924,"z":0.2850338320577658},"position":{"x":-0.14780620368639957,"y":-0.6230709278819978,"z":-0.3883716501255143},"status":"TRACKING","time":1719861768.4745302,"velocity":{"x":0.11773699706990315,"y":-0.33074006205998174,"z":-0.2303034697488478}}
{"acceleration":{"x":1.5215632115979197e-05,"y":0.0009486880966704461,"z":0.00196711689883813},"angularVelocity":{"x":0.2569059133529663,"y":0.16637128591537476,"z":0.32753366231918335},"orientation":{"w":-0.47584695041914915,"x":0.18946524852290342,"y":-0.8146223606614235,"z":0.2721444811493867},"position":{"x":-0.14776927217321248,"y":-0.6203449588297463,"z":-0.38646833119511936},"status":"TRACKING","time":1719861768.508275,"velocity":{"x":0.12890781910281468,"y":-0.3416376405108961,"z":-0.23955099914467393}}
{"acceleration":{"x":-6.371672054540637e-05,"y":0.0009047416252358354,"z":0.0018525175034480462},"angularVelocity":{"x":0.2264654040336609,"y":0.11482755839824677,"z":0.383475661277771},"orientation":{"w":-0.49016701545448405,"x":0.201933453777492,"y":-0.8044510221966756,"z":0.26798756637364735},"position":{"x":-0.1471025209871028,"y":-0.6180078211303865,"z":-0.3843406706250414},"status":"TRACKING","time":1719861768.542023,"velocity":{"x":0.13924241322741107,"y":-0.34802661355907144,"z":-0.24506712474331196}}
{"acceleration":{"x":0.00017425691577402358,"y":0.0011141018888461943,"z":0.002383773891761519},"angularVelocity":{"x":0.26827871799468994,"y":0.30279991030693054,"z":0.3113832473754883},"orientation":{"w":-0.4491303764748212,"x":0.2032757174077076,"y":-0.8318038497222309,"z":0.25507422309671496},"position":{"x":-0.15072617491200338,"y":-0.6164287362589125,"z":-0.38338753844160844},"status":"TRACKING","time":1719861768.575772,"velocity":{"x":0.15217761151648626,"y":-0.3545665431352429,"z":-0.2521589816847783}}
{"acceleration":{"x":0.0009396325072140137,"y":0.045985555319749384,"z":0.10634801557519348},"angularVelocity":{"x":0.8077100515365601,"y":-1.7603349685668945,"z":0.12621045112609863},"orientation":{"w":-0.4779352561525258,"x":0.19078811666142786,"y":-0.8206433337980447,"z":0.24843896007649732},"position":{"x":-0.1423075583931337,"y":-0.629724650390689,"z":-0.39367733102481106},"status":"TRACKING","time":1719861768.609524,"velocity":{"x":0.2709104821921116,"y":-0.42905142126825924,"z":-0.3289133507242484}}
{"acceleration":{"x":-0.05509629480052561,"y":0.1840186194186454,"z":0.42894236414301146},"angularVelocity":{"x":0.4708845615386963,"y":-3.2132599353790283,"z":1.8846863508224487},"orientation":{"w":0.5304070639908153,"x":-0.19848471908206217,"y":0.7870903908632018,"z":-0.2444588389100217},"position":{"x":-0.13061620241929392,"y":-0.6521602930727918,"z":-0.38616235169862556},"status":"TRACKING","time":1719861768.6432774,"velocity":{"x":0.35572172766928956,"y":-0.5240078920173064,"z":-0.3475103938060332}}
{"acceleration":{"x":-0.006703644368707655,"y":0.027122503500449525,"z":0.06555821788701159},"angularVelocity":{"x":0.6922393441200256,"y":-1.3643559217453003,"z":0.10403461754322052},"orientation":{"w":0.5246906287353436,"x":-0.16975165052214983,"y":0.7949551841657934,"z":-0.25284306932226436},"position":{"x":-0.09078226327634334,"y":-0.657921586152492,"z":-0.3626713036094064},"status":"TRACKING","time":1719861768.677028,"velocity":{"x":0.3386413290733076,"y":-0.49605521089898635,"z":-0.39110274524382965}}
{"acceleration":{"x":-0.009788905125455556,"y":0.02270841384222647,"z":0.07395772378447027},"angularVelocity":{"x":0.64805668592453,"y":-1.18716561794281,"z":0.7508590221405029},"orientation":{"w":0.5431973390797276,"x":-0.1772137520236435,"y":0.7964374422647595,"z":-0.1980372952152619},"position":{"x":-0.10344634391725499,"y":-0.6813108666413612,"z":-0.439774122979585},"status":"TRACKING","time":1719861768.7102995,"velocity":{"x":0.35912405829381583,"y":-0.5525413995661164,"z":-0.5080622530935933}}
{"acceleration":{"x":-0.005913282383268184,"y":0.013636039172395436,"z":0.04215294008996887},"angularVelocity":{"x":0.3647380471229553,"y":-0.8819776773452759,"z":0.7549046874046326},"orientation":{"w":0.5437628608997219,"x":-0.1916396904385784,"y":0.7925560981625867,"z":-0.19862135263548594},"position":{"x":-0.09254090159503817,"y":-0.701885786975883,"z":-0.4572845342049388},"status":"TRACKING","time":1719861768.7435718,"velocity":{"x":0.38210218806714163,"y":-0.6510074895252603,"z":-0.5860064784573548}}
{"acceleration":{"x":-0.02744859585336867,"y":0.02932112787819269,"z":0.09328764403169831},"angularVelocity":{"x":0.29700034856796265,"y":-1.4555739164352417,"z":0.982822060585022},"orientation":{"w":0.5997025339978188,"x":-0.20172860394733566,"y":0.7502115760272353,"z":-0.1919492755873578},"position":{"x":-0.07519128020519981,"y":-0.7261090752562613,"z":-0.47825248359103567},"status":"TRACKING","time":1719861768.7768424,"velocity":{"x":0.4341623267632608,"y":-0.7379432271804275,"z":-0.654066622112277}}
{"acceleration":{"x":-0.042544157604876905,"y":0.03269165299001268,"z":0.1058703773821299},"angularVelocity":{"x":0.3006371557712555,"y":-1.612060308456421,"z":0.9605141878128052},"orientation":{"w":0.6358553977376763,"x":-0.19845702936064283,"y":0.7207588930190529,"z":-0.19185635964626885},"position":{"x":-0.08866460031797373,"y":-0.7226954881947548,"z":-0.4726189809453521},"status":"TRACKING","time":1719861768.8101132,"velocity":{"x":0.32832925587351014,"y":-0.5868415512136436,"z":-0.511150673055657}}
{"acceleration":{"x":-0.03168931125525277,"y":0.026120249816210316,"z":0.07614413329781373},"angularVelocity":{"x":0.12604258954524994,"y":-1.3257851600646973,"z":0.9831735491752625},"orientation":{"w":0.6341812440617893,"x":-0.22138578369370696,"y":0.7138974689552405,"z":-0.19786967226543248},"position":{"x":-0.09760961342682568,"y":-0.7221243937944563,"z":-0.4693365275462739},"status":"TRACKING","time":1719861768.8433821,"velocity":{"x":0.2648000694187331,"y":-0.5042785549534098,"z":-0.43191536693857524}}
{"acceleration":{"x":-0.027940371424702515,"y":0.02258205532981823,"z":0.06207849141942995},"angularVelocity":{"x":0.04246020317077637,"y":-1.1878798007965088,"z":0.9476969242095947},"orientation":{"w":0.6405248661769729,"x":-0.23344730407068298,"y":0.7030838413747511,"z":-0.20224461892883625},"position":{"x":-0.10206672169887411,"y":-0.7228083775934653,"z":-0.46775991795422994},"status":"TRACKING","time":1719861768.8766518,"velocity":{"x":0.22098364879347338,"y":-0.45219222167025214,"z":-0.3802355264142954}}
{"acceleration":{"x":-0.01410738670579733,"y":0.011453384146983093,"z":0.038387081456424416},"angularVelocity":{"x":0.2641676962375641,"y":-0.8821611404418945,"z":0.7181282639503479},"orientation":{"w":0.6249156983439739,"x":-0.20821169322265787,"y":0.7298433092792447,"z":-0.18291123024254283},"position":{"x":-0.10810022927786686,"y":-0.7206131685939023,"z":-0.4673629164792746},"status":"TRACKING","time":1719861768.9099195,"velocity":{"x":0.1884085001282751,"y":-0.4103260121491322,"z":-0.3515949788497268}}
{"acceleration":{"x":-0.042257059118524995,"y":0.030648398750756065,"z":0.1308322139113128},"angularVelocity":{"x":1.7764029502868652,"y":1.0638309717178345,"z":-0.0369018018245697},"orientation":{"w":0.617782123175062,"x":-0.19221232747700245,"y":0.7457347035309323,"z":-0.15899349324225034},"position":{"x":-0.11004448649410059,"y":-0.7333773442730757,"z":-0.49633682764279685},"status":"TRACKING","time":1719861768.9431875,"velocity":{"x":0.13473878178075438,"y":-0.4347870542623961,"z":-0.49733938926896337}}
{"acceleration":{"x":-0.00027276982849685154,"y":0.00019094010788698,"z":0.0008290791319512711},"angularVelocity":{"x":0.26564130187034607,"y":-0.211764395236969,"z":-0.41126832365989685},"orientation":{"w":0.6210309812754846,"x":-0.18070193308332033,"y":0.7452373188001841,"z":-0.1621363148248807},"position":{"x":-0.1433743858288467,"y":-0.7713704766471965,"z":-0.5400241881326879},"status":"TRACKING","time":1719861768.976454,"velocity":{"x":0.10558024683587704,"y":-0.5963978278090634,"z":-0.5965019820706059}}
{"acceleration":{"x":-0.005930162212146173,"y":0.0033165589255251056,"z":0.0158995069599218},"angularVelocity":{"x":0.5041282773017883,"y":-0.5935685634613037,"z":-0.02222367189824581},"orientation":{"w":0.6379081368219719,"x":-0.17460692583501097,"y":0.7338447803360595,"z":-0.1551031827551607},"position":{"x":-0.18191282039197926,"y":-0.7989956879617278,"z":-0.5715455543536362},"status":"TRACKING","time":1719861769.009721,"velocity":{"x":0.017094827465922995,"y":-0.5972864198980873,"z":-0.6372357617222616}}
{"acceleration":{"x":-0.003480941703565791,"y":0.0018214981129297295,"z":0.01003431663805763},"angularVelocity":{"x":0.3326480984687805,"y":-0.026083365082740784,"z":0.7243561744689941},"orientation":{"w":0.6297206625591347,"x":-0.20520863187117547,"y":0.7380539653862034,"z":-0.12890758250394876},"position":{"x":-0.18221741245835937,"y":-0.8195164416455792,"z":-0.5940609926451649},"status":"TRACKING","time":1719861769.0429862,"velocity":{"x":0.03614275782678202,"y":-0.684922043954477,"z":-0.7282959798019714}}
{"acceleration":{"x":-0.004884888128570677,"y":0.0023561494141141593,"z":0.01660777270190718},"angularVelocity":{"x":0.5957092642784119,"y":0.2840109169483185,"z":0.35548877716064453},"orientation":{"w":0.616766861836639,"x":-0.18488999292405883,"y":0.7562900097203485,"z":-0.11592781104151396},"position":{"x":-0.18201267963093132,"y":-0.8425690646947103,"z":-0.6196438581580731},"status":"TRACKING","time":1719861769.0762515,"velocity":{"x":0.06621620373268837,"y":-0.7735165212089072,"z":-0.8224564235033454}}
{"acceleration":{"x":-0.0029430374734099166,"y":0.0014065010031683732,"z":0.009826809848349926},"angularVelocity":{"x":0.44561514258384705,"y":0.2067861706018448,"z":0.34098541736602783},"orientation":{"w":0.6182758802045184,"x":-0.18968335822384064,"y":0.7540574870205171,"z":-0.114682055261327},"position":{"x":-0.17849144751793455,"y":-0.8721714547666743,"z":-0.6498918318856954},"status":"TRACKING","time":1719861769.1095154,"velocity":{"x":0.11789498982799557,"y":-0.8831854009357457,"z":-0.9257854017333562}}
{"acceleration":{"x":-0.0035675658801316928,"y":0.0012208718048908236,"z":0.009920243497588202},"angularVelocity":{"x":0.466396301984787,"y":-0.10089821368455887,"z":0.3240628242492676},"orientation":{"w":0.6407513382928969,"x":-0.18221953198915797,"y":0.7375822537317108,"z":-0.11047946061204449},"position":{"x":-0.1720866151245997,"y":-0.9022762377961642,"z":-0.6809114534163153},"status":"TRACKING","time":1719861769.1427796,"velocity":{"x":0.1695108713400483,"y":-0.984624822290341,"z":-1.0254550273310024}}
{"acceleration":{"x":-0.0014908692432238555,"y":0.000671157081781632,"z":0.003821945414550308},"angularVelocity":{"x":0.23952122032642365,"y":-0.08471900224685669,"z":0.29909780621528625},"orientation":{"w":0.6448132249187114,"x":-0.19780744907161824,"y":0.7266359166935206,"z":-0.13072066429656587},"position":{"x":-0.17480279515937908,"y":-0.8523892294196301,"z":-0.6132059019585142},"status":"TRACKING","time":1719861769.176042,"velocity":{"x":0.15348163369481177,"y":-0.7210205730021839,"z":-0.7077592836595237}}
{"acceleration":{"x":-0.0016116117154815989,"y":0.0006761408865172548,"z":0.004210504723018879},"angularVelocity":{"x":0.33490419387817383,"y":-0.03330395743250847,"z":0.14857344329357147},"orientation":{"w":0.6451359850070464,"x":-0.1777830821264879,"y":0.7314161921387629,"z":-0.13123499192258264},"position":{"x":-0.17803404809648798,"y":-0.8260801364035716,"z":-0.5783755286149441},"status":"TRACKING","time":1719861769.209305,"velocity":{"x":0.1396728181741041,"y":-0.5906683283586467,"z":-0.5606098450084902}}
{"acceleration":{"x":-0.000705062743095676,"y":0.00039500576691674,"z":0.002032540741209043},"angularVelocity":{"x":0.22186921536922455,"y":0.09946838021278381,"z":0.07799810916185379},"orientation":{"w":0.630106263605425,"x":-0.18284236663697498,"y":0.7407313763443228,"z":-0.14439984215944887},"position":{"x":-0.18190630452656253,"y":-0.809799953620336,"z":-0.5551313429889967},"status":"TRACKING","time":1719861769.2425659,"velocity":{"x":0.13045748969237603,"y":-0.5196301400568499,"z":-0.47862523991317896}}
{"acceleration":{"x":-0.002180125076133159,"y":0.0007225253536451884,"z":0.0059846729617704306},"angularVelocity":{"x":0.3811548948287964,"y":0.07484135031700134,"z":0.21236388385295868},"orientation":{"w":0.6425771221924126,"x":-0.18018009506880253,"y":0.7365132744001919,"z":-0.11035171641330828},"position":{"x":-0.1837291221907008,"y":-0.7953546308407732,"z":-0.5385106777704927},"status":"TRACKING","time":1719861769.2758276,"velocity":{"x":0.13486230303653668,"y":-0.4687270257895339,"z":-0.43290851574233835}}
{"acceleration":{"x":-0.0016788642566296888,"y":0.0005828149070856932,"z":0.003669860319497895},"angularVelocity":{"x":0.25941988825798035,"y":-0.12844976782798767,"z":0.20030193030834198},"orientation":{"w":0.6678906745380049,"x":-0.18463042878286848,"y":0.709175719429508,"z":-0.1300115313653543},"position":{"x":-0.18293219757587825,"y":-0.7883372157694305,"z":-0.525539656787002},"status":"TRACKING","time":1719861769.3090875,"velocity":{"x":0.14614586413355488,"y":-0.44761579226555764,"z":-0.40464872442505945}}
{"acceleration":{"x":-0.000905184091808557,"y":0.0003730415364473648,"z":0.002092779435744641},"angularVelocity":{"x":0.24209201335906982,"y":-0.07521986216306686,"z":0.07558917254209518},"orientation":{"w":0.6595677862299822,"x":-0.17006235077652443,"y":0.7179105142735068,"z":-0.14371210845685628},"position":{"x":-0.18473733584462412,"y":-0.7819236017130238,"z":-0.5156868622953227},"status":"TRACKING","time":1719861769.3423476,"velocity":{"x":0.13262762691193794,"y":-0.4293720787343257,"z":-0.3844348764604341}}
{"acceleration":{"x":-0.0019212938429935466,"y":0.0005462463199788844,"z":0.003984147556858413},"angularVelocity":{"x":0.31041887402534485,"y":-0.15432210266590118,"z":0.11881186813116074},"orientation":{"w":0.6782312799032196,"x":-0.16188854863693772,"y":0.7051510301152694,"z":-0.1286701617754122},"position":{"x":-0.1840787656977943,"y":-0.7749628384583341,"z":-0.5070749155683703},"status":"TRACKING","time":1719861769.3756063,"velocity":{"x":0.12269333603064501,"y":-0.41478369099071094,"z":-0.3718314571619047}}
{"acceleration":{"x":-0.002671652091660423,"y":0.0007045230130277127,"z":0.004715083414113629},"angularVelocity":{"x":0.22449910640716553,"y":-0.25266891717910767,"z":0.2245357483625412},"orientation":{"w":0.6989229233233303,"x":-0.18512924422487165,"y":0.6787293315884009,"z":-0.12868555151161473},"position":{"x":-0.18228440314519073,"y":-0.7717721684871138,"z":-0.5002412057275076},"status":"TRACKING","time":1719861769.408865,"velocity":{"x":0.11849688358101347,"y":-0.4089398078823646,"z":-0.3631292541656384}}
{"acceleration":{"x":-0.006129822493445668,"y":0.0013107568954364905,"z":0.008376269562955611},"angularVelocity":{"x":0.19469456374645233,"y":-0.4565001130104065,"z":0.2548207640647888},"orientation":{"w":0.7370395326298238,"x":-0.18376409238070252,"y":0.636056239944879,"z":-0.13577750777215947},"position":{"x":-0.17902621217159265,"y":-0.7681557288519337,"z":-0.4927210948293065},"status":"TRACKING","time":1719861769.4421222,"velocity":{"x":0.10706170851160135,"y":-0.3981537687660139,"z":-0.34802032810050176}}
{"acceleration":{"x":-0.0057891156522628,"y":0.0013742068608637843,"z":0.00760868621122044},"angularVelocity":{"x":0.1851535588502884,"y":-0.46971285343170166,"z":0.1807994395494461},"orientation":{"w":0.7421747220345424,"x":-0.16954363132523975,"y":0.631012618627625,"z":-0.14917876591898707},"position":{"x":-0.17828429923462227,"y":-0.7660300952989572,"z":-0.48789328336829674},"status":"TRACKING","time":1719861769.4753797,"velocity":{"x":0.07805125146284318,"y":-0.3901723188391427,"z":-0.33934823129858005}}
{"acceleration":{"x":-0.004781932311779948,"y":0.0011263587067801399,"z":0.006417616538540088},"angularVelocity":{"x":0.13609136641025543,"y":-0.39860033988952637,"z":0.25890907645225525},"orientation":{"w":0.7370720905454681,"x":-0.1962274016335728,"y":0.6312651704309211,"z":-0.14044005802118642},"position":{"x":-0.17835775264776485,"y":-0.7647305118518755,"z":-0.48526986347673123},"status":"TRACKING","time":1719861769.5086355,"velocity":{"x":0.05637703104747839,"y":-0.38387167106283965,"z":-0.33609155028603543}}
{"acceleration":{"x":-0.010193447111551726,"y":0.0016637165502242943,"z":0.010659883052511195},"angularVelocity":{"x":0.1323232203722,"y":-0.5708367228507996,"z":0.31978392601013184},"orientation":{"w":0.7763566664859449,"x":-0.19751349739186952,"y":0.5827205330355552,"z":-0.13673012430866488},"position":{"x":-0.17518170014344403,"y":-0.762063914280315,"z":-0.4796509306712724},"status":"TRACKING","time":1719861769.5418918,"velocity":{"x":0.0427562586475446,"y":-0.37027808568617904,"z":-0.320821662335156}}
{"acceleration":{"x":-0.008704171368121467,"y":0.0016160031440320773,"z":0.009165746150012881},"angularVelocity":{"x":0.11395954340696335,"y":-0.5337263345718384,"z":0.2896074056625366},"orientation":{"w":0.7738235756921932,"x":-0.19657898293333867,"y":0.5846692476915831,"z":-0.14392792930922776},"position":{"x":-0.1754254867824932,"y":-0.7614423973854335,"z":-0.47738257634966386},"status":"TRACKING","time":1719861769.5751462,"velocity":{"x":0.017723365025480994,"y":-0.35739989844600506,"z":-0.31067927381438104}}
{"acceleration":{"x":-0.0063458341827539975,"y":0.0013131186416822488,"z":0.007130669471774786},"angularVelocity":{"x":0.10291921347379684,"y":-0.4542180597782135,"z":0.2717460095882416},"orientation":{"w":0.7630548983409459,"x":-0.2001364082823518,"y":0.5971686191154735,"z":-0.14519599418681972},"position":{"x":-0.17663435845518277,"y":-0.7617789218598489,"z":-0.4768955720563816},"status":"TRACKING","time":1719861769.608401,"velocity":{"x":-0.002862851878409931,"y":-0.34903496068119416,"z":-0.3064237783159219}}
{"acceleration":{"x":-0.0061352475621769985,"y":0.0013812360304186406,"z":0.006686113963380705},"angularVelocity":{"x":0.08371951431035995,"y":-0.4528641700744629,"z":0.2521350681781769},"orientation":{"w":0.7659106998413897,"x":-0.1992243487265806,"y":0.591649466774214,"z":-0.15375618568588748},"position":{"x":-0.17683683694970478,"y":-0.7616569254007185,"z":-0.47490699095766314},"status":"TRACKING","time":1719861769.6416545,"velocity":{"x":-0.01720739302381373,"y":-0.3374322656949089,"z":-0.29666049982550236}}
{"acceleration":{"x":-0.004853567317681561,"y":0.0010222681132478239,"z":0.005636532659582532},"angularVelocity":{"x":0.106622613966465,"y":-0.39081498980522156,"z":0.25069501996040344},"orientation":{"w":0.7585065493644475,"x":-0.19816506212029453,"y":0.6038323006284108,"z":-0.14416854688754163},"position":{"x":-0.17833623632443363,"y":-0.7608028286840278,"z":-0.4743788183289112},"status":"TRACKING","time":1719861769.6749096,"velocity":{"x":-0.0263877249973214,"y":-0.3250736644637724,"z":-0.2892752521190565}}
{"acceleration":{"x":-0.004751330031282924,"y":0.0006316513015528956,"z":0.005734080915564703},"angularVelocity":{"x":0.2118110954761505,"y":-0.3686394691467285,"z":0.20227494835853577},"orientation":{"w":0.761373151884212,"x":-0.16053644603052578,"y":0.6155814002633598,"z":-0.12489239998203465},"position":{"x":-0.17971148940529777,"y":-0.7593367537363795,"z":-0.4742824600135432},"status":"TRACKING","time":1719861769.7081845,"velocity":{"x":-0.027865746796930737,"y":-0.32721847446311186,"z":-0.29511815130385965}}
{"acceleration":{"x":-0.0037863034978305177,"y":0.000714137414632986,"z":0.004630705365684417},"angularVelocity":{"x":0.19654648005962372,"y":-0.35556724667549133,"z":0.13263869285583496},"orientation":{"w":0.7570281764959162,"x":-0.1441234397738464,"y":0.6205419577669368,"z":-0.14513459662425746},"position":{"x":-0.1807149173223669,"y":-0.7599895069416719,"z":-0.4729870527167074},"status":"TRACKING","time":1719861769.7414594,"velocity":{"x":-0.04333765121698039,"y":-0.3339137241196707,"z":-0.3035849521216339}}
{"acceleration":{"x":-0.0029908102400132445,"y":0.0008155969534669202,"z":0.0036499017110925708},"angularVelocity":{"x":0.14675791561603546,"y":-0.34744200110435486,"z":0.08464264124631882},"orientation":{"w":0.752280627730535,"x":-0.14160067041268193,"y":0.620064192029942,"z":-0.17188106764673317},"position":{"x":-0.18165846517594672,"y":-0.7616216648751637,"z":-0.471801920307127},"status":"TRACKING","time":1719861769.7747324,"velocity":{"x":-0.05786193260988011,"y":-0.33621716195428697,"z":-0.3063923159825897}}
{"acceleration":{"x":-0.003447985436923961,"y":0.0007514221981259646,"z":0.004065384416997689},"angularVelocity":{"x":0.18463964760303497,"y":-0.35780230164527893,"z":0.08827261626720428},"orientation":{"w":0.7612927819922355,"x":-0.12816248329015645,"y":0.6151412399572316,"z":-0.16002666633867665},"position":{"x":-0.18224086173633536,"y":-0.761282236353305,"z":-0.47134969333206284},"status":"TRACKING","time":1719861769.808006,"velocity":{"x":-0.07184928777336524,"y":-0.3385645393222947,"z":-0.3120255732981876}}
{"acceleration":{"x":-0.004591629488620479,"y":0.0010254495661965407,"z":0.004730678685661287},"angularVelocity":{"x":0.1393367350101471,"y":-0.4094157814979553,"z":0.12517282366752625},"orientation":{"w":0.7787285050367145,"x":-0.1441418178886072,"y":0.5871158506186814,"z":-0.16762946121945174},"position":{"x":-0.18161522854522794,"y":-0.7618206661628987,"z":-0.46900672391043835},"status":"TRACKING","time":1719861769.841278,"velocity":{"x":-0.08828438640694378,"y":-0.33632043666555766,"z":-0.31091503758747846}}
{"acceleration":{"x":-0.00502677952056024,"y":0.0008999444279628077,"z":0.005026281628755552},"angularVelocity":{"x":0.15994147956371307,"y":-0.41149643063545227,"z":0.1459377110004425},"orientation":{"w":0.7860758717887757,"x":-0.1419392208936811,"y":0.5813513395133652,"z":-0.15481670106289103},"position":{"x":-0.1823813357834111,"y":-0.761018733815115,"z":-0.4680801355335508},"status":"TRACKING","time":1719861769.8745506,"velocity":{"x":-0.10311626530753937,"y":-0.332364319507533,"z":-0.31128829318784074}}
{"acceleration":{"x":-0.2253200952432587,"y":0.04348291666004277,"z":0.18625075948084321},"angularVelocity":{"x":-1.439642310142517,"y":-2.726015090942383,"z":0.4053185284137726},"orientation":{"w":0.8085137762226433,"x":-0.15711171416640915,"y":0.5412492676732624,"z":-0.1693228546431485},"position":{"x":-0.18468461719862153,"y":-0.7737726888864345,"z":-0.4771040875430984},"status":"TRACKING","time":1719861769.9078214,"velocity":{"x":-0.10086328154028029,"y":-0.4233612678979566,"z":-0.30937412483272386}}
with python vio_visu.py
![Figure_1](https://github.com/SpectacularAI/sdk/assets/34170216/82dea970-050e-44b7-95e9-017db5a2cbc8)

the imu values are flipping like crazy and i tested on realsense_viewer and look normal. 

there any easy fix i can try? i wanted to use the visualizer to map a huge area and make sure its getting all place ...  in a outside area ... i using 3.2 usb cable tested the connection and with 2 realsense cameras the D455 and the D345i. Do you have any option to use ZED c
![Captura de tela de 2024-07-01 16-32-15](https://github.com/SpectacularAI/sdk/assets/34170216/7d0b1896-b995-4890-9750-7647455a52e0)

i tryed using 
./sai-record-realsense --recording_only --no_preview .. i made a small test but still and when i try to move the camera it's lost track
https://drive.google.com/drive/folders/1Lu4P9JHIPX7V5fBiwHVHEGHYbzRXYLav?usp=sharing

**Comment by YecidMorenoUSP** [comment]
Hey, I found the solution with @RenanMoreiraPinto , was only downgrade our realsense v2.51, and the firmware of the camera to 5.15.00.02, and it worked perfectly, thank you very much.

**Comment by jehontan** [comment]
Had a similar problem with firmware 5.16.0.1. Downgrading resolved the issue.
