### ISSUE TITLE
Segmentation Fault when running vio_jsonl on Intel Realsense d435i

### ISSUE THREAD

**Issue by 123orrin** [SpectacularAI/sdk#45]
Hello,

I am following the examples in the [spectacularAI realsense documentation](https://spectacularai.github.io/docs/sdk/wrappers/realsense.html) and after building the examples using CMake, I run into a `Segmentation Fault (core dumped)` error when running `./vio_jsonl` in the terminal.

I am using the latest version of the spectacularAI SDK and have also tried with an older version (1.31.0), which also produces the same problem. The following warning is present when building but I don't believe this is what caused the issue: `/usr/bin/ld: warning: librealsense2.so.2.51, needed by /usr/local/lib/libspectacularAI_realsensePlugin.so.1.31.0, may conflict with librealsense2.so.2.55`

Any advice on this matter?

----------------------------
Additional Info
Ubuntu 22.04 6.5.0-45-generic
Intel Realsense d435i
SpectacularAI SDK v1.34.0
Librealsense SDK 2.0 v2.55.1

**Comment by Bercon** [comment]
The SDK requires Librealsense 2.51.1 and using newer is likely the cause of the issue. We'll update librealsense to a more up to date version in the next release

**Comment by 123orrin** [comment]
@Bercon Thank you for the help. I can confirm that using librealsense 2.51.1 fixes this issue.
